//! Registers the app's own IPC commands with Tauri's ACL so that the
//! capabilities in `capabilities/*.json` can reference `allow-<command>`
//! permissions (autogenerated into `permissions/autogenerated/`).
use tauri_build::{AppManifest, Attributes};

const COMMANDS: &[&str] = &[
    // page bridge (remote arena.ai origin may call these)
    "fetch_trace",
    "proxy_get",
    "get_app_info",
    "page_event",
    // shell only
    "arena_command",
    "list_accounts",
    "save_account",
    "delete_account",
    "list_tabs",
    "open_tab",
    "close_tab",
    "activate_tab",
    "pick_account",
    "probe_proxy",
];

fn main() {
    tauri_build::try_build(
        Attributes::new().app_manifest(AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
