//! Registers the app's own IPC commands with Tauri's ACL so that the
//! capabilities in `capabilities/*.json` can reference `allow-<command>`
//! permissions (autogenerated into `permissions/autogenerated/`).
use tauri_build::{AppManifest, Attributes};

const COMMANDS: &[&str] = &[
    "fetch_trace",
    "proxy_get",
    "arena_command",
    "get_app_info",
    "page_event",
];

fn main() {
    tauri_build::try_build(
        Attributes::new().app_manifest(AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
