#!/usr/bin/env bash
# Copy src-tauri/android-overlay/** over the Gradle project generated by
# `tauri android init` (src-tauri/gen/android). Run after init, before build.
# Idempotent; fails loudly if the generated project is missing.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
overlay="$root/src-tauri/android-overlay"
gen="$root/src-tauri/gen/android"
[ -d "$gen" ] || { echo "apply-android-overlay: $gen not found — run 'tauri android init' first" >&2; exit 1; }
[ -d "$overlay" ] || { echo "apply-android-overlay: nothing to apply"; exit 0; }
# The template places MainActivity under java/<package path>/; make sure the
# generated one is gone so two activities never coexist.
find "$gen/app/src/main" -name MainActivity.kt -not -path "*/com/ati/arenakit/*" -print -delete || true
(cd "$overlay" && find . -type f -print0) | while IFS= read -r -d '' f; do
  mkdir -p "$gen/$(dirname "$f")"
  cp -f "$overlay/$f" "$gen/$f"
  echo "overlay → gen/android/${f#./}"
done
